version: '3.4'

services:

  scaniatest.api:
    image: ${DOCKER_REGISTRY-}scaniatestapi
    build:
      context: .
      dockerfile: ScaniaTest.Api/Dockerfile
    ports:
         - 7001:80
    volumes:
      - databasetest:/database
      - logs:/serviceslogs
    networks:
        - mynetwork1

  scaniatest.customers:
    image: ${DOCKER_REGISTRY-}scaniatestcustomers
    build:
      context: .
      dockerfile: ScaniaTest.Customers/Dockerfile
    ports:
         - 7002:80
    volumes:
      - databasetest:/database
      - logs:/serviceslogs
    networks:
        - mynetwork1

  scaniatest.simulator:
    image: ${DOCKER_REGISTRY-}scaniatestsimulator
    build:
      context: .
      dockerfile: ScaniaTest.Simulator/Dockerfile
    ports:
         - 7003:80
    volumes:
      - databasetest:/database
      - logs:/serviceslogs
    networks:
       - mynetwork1

# rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
        mynetwork1:
            ipv4_address: 192.168.1.10


# frontend
  frontend:
        build:
            context: ./ScaniaTest.Frontend
        container_name: angular
        ports:
            - 4200:80
        networks:
            - mynetwork1

volumes:
  rabbitmqdata:
  databasetest:
  logs:

networks:
  mynetwork1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
